### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by marcverlooy** [sculptui/vscode#1]
- Issue Type: `Performance`
- Extension Name: `sculptui-vscode`
- Extension Version: `0.6.5`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.58.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\marcv\AppData\Local\Temp\ardevia.sculptui-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanyWyss** [comment]
Thanks for notifying. I would like to look into it. Can you attach c:\Users\marcv\AppData\Local\Temp\ardevia.sculptui-vscode-unresponsive.cpuprofile.txt ?

**Comment by marcverlooy** [comment]
I am very,very sorry, but looked for the file during 40 minutes(even in Windows 11 explorer) but could not find it!
