### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by bodhihawken** [sculptui/vscode#3]
**Describe the bug**
Sculpt UI on start executes the command with no result. and under runtime status shows:
"Cannot read property 'forEach' of undefined"

**Expected behaviour**
SculptUI should open and launch a browser page.

**Desktop (please complete the following information):**

**Additional context**
Assuming its something to do with an invalid project etc
Project does start correctly, and build correctly.

**Comment by lybko25** [comment]
@Hawki101, hello.
Is there any error messages with error stack? We need more information to resolve your issue, beacuse there a lot of places, where we use forEach in our extension. 
Or can you, please, provide us with link to your repo?

**Comment by bodhihawken** [comment]
I can't seem to get any more error messages from the Stack, just a very loose error message.

Also, I cant provide a link to this repo!

I'll close this, and ill have a go in the future at the starting point of a project!
